GOOGLE_API_KEY=AIzaSyCzQeFhPiTWd-TVerRJwrpVfZUv6diGFI4
ASTRA_DB_APPLICATION_TOKEN=AstraCS:UyqdYWsoUMRJPxiyYNUTaBiR:4648af223aa8dffb0af8531b1a660e65900f3624f6f92fb4476f136bd789180c
ASTRA_DB_API_ENDPOINT=https://f5b01e62-56cf-470a-8a93-f5b8d38883c0-us-east-2.apps.astra.datastax.com
ASTRA_DB_NAMESPACE=default_keyspace